# Generated by Django 5.2.1 on 2025-05-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefono', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacto',
            options={'permissions': (('puede_ver_contactos', 'Ver contactos'), ('puede_escribir_contactos', 'Escribir contactos'))},
        ),
        migrations.AddField(
            model_name='contacto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
    ]
