# Generated by Django 5.2.1 on 2025-05-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefono', '0002_alter_contacto_options_contacto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='contactos/'),
        ),
    ]
